### ISSUE TITLE
Rule `count_matrix` job submission fails when used with `--cluster` parameter

### ISSUE THREAD

**Issue by ManavalanG** [snakemake-workflows/rna-seq-star-deseq2#9]
Rule `count_matrix` in diffexp.smk works as expected when run locally, but it fails when used with lsf cluster using `--cluster "bsub -o cluster.log"`. Job submission never happens in this case, and my preliminary debugging shows this happens when parsing `params`; commenting out `params` section lead to successful job submission. Below is the output I get:

    Building DAG of jobs...
    Using shell: /usr/bin/bash
    Provided cluster nodes: 10
    Job counts:
            count   jobs
            1       all
            1       count_matrix
            1       deseq2
            1       deseq2_init
            1       pca
            5

    rule count_matrix:
        input: star/A-lane1/ReadsPerGene.out.tab, star/B-lane1/ReadsPerGene.out.tab
        output: counts/all.tsv
        jobid: 4

        Traceback (most recent call last):
    File "yoyoyo/.virtualenvs/rna-seq-star-deseq2-ueAqQq5F/lib/python3.6/site-packages/snakemake/__init__.py", line 541, in snakemake
        report=report)
    File "yoyoyo/.virtualenvs/rna-seq-star-deseq2-ueAqQq5F/lib/python3.6/site-packages/snakemake/workflow.py", line 653, in execute
        success = scheduler.schedule()
    File "yoyoyo/.virtualenvs/rna-seq-star-deseq2-ueAqQq5F/lib/python3.6/site-packages/snakemake/scheduler.py", line 286, in schedule
        self.run(job)
    File "yoyoyo/.virtualenvs/rna-seq-star-deseq2-ueAqQq5F/lib/python3.6/site-packages/snakemake/scheduler.py", line 302, in run
        error_callback=self._error)
    File "yoyoyo/.virtualenvs/rna-seq-star-deseq2-ueAqQq5F/lib/python3.6/site-packages/snakemake/executors.py", line 642, in run
        jobfailed=jobfailed)
    File "yoyoyo/.virtualenvs/rna-seq-star-deseq2-ueAqQq5F/lib/python3.6/site-packages/snakemake/executors.py", line 534, in write_jobscript
        **kwargs)
    File "yoyoyo/.virtualenvs/rna-seq-star-deseq2-ueAqQq5F/lib/python3.6/site-packages/snakemake/executors.py", line 514, in format_job
        cluster=self.cluster_params(job))),
    File "/python-3.6.0/lib/python3.6/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
    File "/python-3.6.0/lib/python3.6/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
    File "/python-3.6.0/lib/python3.6/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
    File "/python-3.6.0/lib/python3.6/json/encoder.py", line 180, in default
        o.__class__.__name__)
    TypeError: Object of type 'DataFrame' is not JSON serializable

**Comment by johanneskoester** [comment]
Fixed in 5.2.1

**Comment by jbalberge** [comment]
Adding `localrules: all, count_matrix` to _Snakefile_ is another convenient solution :-)
